apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: critical-app
  name: critical-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: critical-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: critical-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        ports:
        - containerPort: 80
        resources: 
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi  
      priorityClassName: critical-apps
status: {}
