apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical-apps
value: 2000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class will cause lower priority pods to be preempted."